
const profile=DB.get('profile',{weight:77.5,calories:2500,bf:11.4,waist:80});
['weight','calories','bf','waist'].forEach(k=>{let e=document.getElementById(k);if(e)e.textContent=profile[k]});
(async function hydrateDashboard(){
 try{
  const rows=await BBDB.latestMetrics(); if(!rows.length)return;
  const latest=(field)=>rows.find(x=>x[field]!=null)?.[field];
  const map={weight:'weight_kg',bf:'body_fat_pct',waist:'waist_cm'};
  Object.entries(map).forEach(([id,field])=>{const v=latest(field),el=document.getElementById(id);if(v!=null&&el)el.textContent=v});
 }catch(e){console.warn('Cloud metrics unavailable',e)}
})();
async function editMetric(k,label){let v=prompt(label,profile[k]);if(v!==null&&!isNaN(parseFloat(v))){v=parseFloat(v);profile[k]=v;DB.set('profile',profile);DB.set('bodyLog',[{type:k,value:v,date:new Date().toISOString()},...DB.get('bodyLog',[])]);try{let saved=null;if(k==='weight')saved=await BBDB.saveBodyMetrics({weight_kg:v,source:'manual'});else if(k==='waist')saved=await BBDB.saveBodyMetrics({waist_cm:v,source:'manual'});if(saved)await BBDB.coachReview(k==='weight'?'weight':'general',{metric:k,value:v},saved.id)}catch(e){alert('Saved on this device, but cloud save failed: '+e.message)}location.reload()}}

['photoUpload'].forEach(id=>{let el=document.getElementById(id);if(el)el.onchange=()=>{if(el.files[0]){let log=DB.get('uploads',[]);log.unshift({type:id,name:el.files[0].name,date:new Date().toISOString()});DB.set('uploads',log);document.getElementById('uploads').textContent='Recorded: '+el.files[0].name+' · '+new Date().toLocaleString();}}});
let inbody=document.getElementById('inbodyUpload');if(inbody)inbody.onchange=async()=>{if(!inbody.files[0])return;const box=document.getElementById('uploads');box.textContent='InBody selected. Enter the values from the report to save them to your coaching history.';const weight=prompt('InBody weight (kg)');if(weight===null)return;const bf=prompt('InBody body fat (%)');if(bf===null)return;const muscle=prompt('InBody skeletal muscle mass (kg) — leave blank if unavailable','');try{const saved=await BBDB.saveBodyMetrics({weight_kg:Number(weight),body_fat_pct:Number(bf),skeletal_muscle_kg:muscle===''?null:Number(muscle),source:'inbody',notes:'Imported from '+inbody.files[0].name});box.textContent='InBody saved. Coach reviewing…';await BBDB.coachReview('weight',{source:'inbody',weight_kg:Number(weight),body_fat_pct:Number(bf),skeletal_muscle_kg:muscle===''?null:Number(muscle)},saved.id);box.textContent='InBody saved + coach review ✓';setTimeout(()=>location.reload(),600)}catch(e){box.textContent='InBody not saved: '+e.message}};

let cycleProgramme=null;
async function renderCycle(){
 const box=document.getElementById('week');if(!box)return;
 const cycle=[{name:'Pull A',rest:false},{name:'Legs + Abs',rest:false},{name:'Rest / Steps',rest:true},{name:'Push A',rest:false},{name:'Shoulders + Arms',rest:false},{name:'Pull B + Upper Chest',rest:false},{name:'Rest',rest:true}],days=['MON','TUE','WED','THU','FRI','SAT','SUN'];
 let history=[],block=null;try{[history,block]=await Promise.all([BBDB.cloudHistory(),BBDB.activeBlock()])}catch(e){console.warn(e)}
 const now=new Date(),jsDay=now.getDay(),todayIdx=(jsDay+6)%7,monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-todayIdx);
 const ymd=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day};
 const completedNames=new Set(history.filter(w=>w.status==='completed'&&((w.completed_at&&new Date(w.completed_at)>=monday)||w.actual_date>=ymd(monday))).map(w=>w.name));
 const matches=(planned)=>completedNames.has(planned)||(planned==='Legs + Abs'&&completedNames.has('Legs'))||(planned==='Pull B + Upper Chest'&&completedNames.has('Pull B'));
 let next=-1;for(let i=todayIdx;i<cycle.length;i++){if(!cycle[i].rest&&!matches(cycle[i].name)){next=i;break}}
 if(next<0){for(let i=0;i<cycle.length;i++){if(!cycle[i].rest&&!matches(cycle[i].name)){next=i;break}}}
 let stage='';if(block?.start_date){const s=new Date(block.start_date+'T00:00:00'),day=Math.max(0,Math.floor((new Date(now.getFullYear(),now.getMonth(),now.getDate())-s)/86400000)),dur=Number(block.duration_weeks||12),wk=Math.min(dur,Math.floor(day/7)+1),rw=(block.recovery_weeks||[6,12]).map(Number),rec=rw.includes(wk),phase=rec?'RECOVERY WEEK':wk<rw[0]?'BUILD 1':'BUILD 2',nr=rw.find(x=>x>wk);stage='<div class="blockPhase"><span class="blockKicker">12-WEEK HYPERTROPHY BLOCK</span><div class="blockHeadline"><strong>Week '+wk+' <em>of '+dur+'</em></strong><span class="phaseBadge '+(rec?'recovery':'')+'">'+phase+'</span></div><div class="blockTrack segmented"><i style="width:'+Math.round(wk/dur*100)+'%"></i><span class="weekDivider" style="left:8.333333333333332%"></span><span class="weekDivider" style="left:16.666666666666664%"></span><span class="weekDivider" style="left:25%"></span><span class="weekDivider" style="left:33.33333333333333%"></span><span class="weekDivider" style="left:41.66666666666667%"></span><span class="weekDivider" style="left:50%"></span><span class="weekDivider" style="left:58.333333333333336%"></span><span class="weekDivider" style="left:66.66666666666666%"></span><span class="weekDivider" style="left:75%"></span><span class="weekDivider" style="left:83.33333333333334%"></span><span class="weekDivider" style="left:91.66666666666666%"></span></div><div class="blockStops segmentedLabels"><span class="phaseLabel buildOne"><b>W1–5</b>Build</span><span class="phaseLabel recoveryOne"><b>W6</b>Rest</span><span class="phaseLabel buildTwo"><b>W7–11</b>Build</span><span class="phaseLabel recoveryTwo"><b>W12</b>Rest</span></div><p class="blockCountdown">'+(rec?'Recovery Week · reduce training stress and prioritise recovery.':nr?'<b>'+(nr-wk)+'</b> week'+(nr-wk===1?'':'s')+' until Recovery Week':'Final week of block.')+'</p></div>'}
 box.innerHTML=stage+cycle.map((s,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const done=!s.rest&&matches(s.name),past=i<todayIdx&&!done,cls=done?'completed':i===next?'today':'';return `<div class='${cls} cycleRow' data-cycle='${i}'><span>${days[i]} ${d.getDate()}/${d.getMonth()+1}</span><b>${s.name}</b>${done?'<span class="statuspill">DONE</span>':i===next?'<span class="statuspill">NEXT</span>':s.rest?'<span class="muted">REST</span>':past?'<span class="muted">MISSED / MOVE</span>':''}</div><div class="cycleExpand hidden" id="cycle-${i}"></div>`}).join('');
 document.querySelectorAll('[data-cycle]').forEach(r=>r.onclick=async()=>{let i=+r.dataset.cycle,out=document.getElementById('cycle-'+i);document.querySelectorAll('.cycleExpand').forEach(x=>{if(x!==out)x.classList.add('hidden')});if(!out.classList.contains('hidden')){out.classList.add('hidden');return}let s=cycle[i];if(s.rest){out.innerHTML='<p class="smallnote">Recovery / steps day. No programmed lifting.</p>'}else{let p=await BBDB.programme(),ps=p?.sessions?.find(x=>x.name===s.name);out.innerHTML=ps?'<p class="smallnote">'+(ps.emphasis||'Programmed session')+'</p><a class="primaryLink" href="workout.html?session='+encodeURIComponent(ps.id)+'">Train this session today →</a>':'<p class="smallnote">Session details unavailable.</p>'}out.classList.remove('hidden')})
}
renderCycle();
let restBtn=document.getElementById('restBtn'), modal=document.getElementById('rescheduleModal');
if(restBtn) restBtn.onclick=()=>modal.classList.remove('hidden');
let cancel=document.getElementById('cancelReschedule'); if(cancel) cancel.onclick=()=>modal.classList.add('hidden');
document.querySelectorAll('[data-rest]').forEach(b=>b.onclick=async()=>{
  let sched=DB.get('schedule',{cursor:0,reschedules:[]});sched.reschedules=sched.reschedules||[];sched.reschedules.push({sessionIndex:sched.cursor,action:'Rest today — session kept next',reason:b.dataset.rest,date:new Date().toISOString()});DB.set('schedule',sched);try{await BBDB.saveScheduleState(sched)}catch(e){}modal.classList.add('hidden');await renderCycle();
});
let skipSession=document.getElementById('skipSession');if(skipSession)skipSession.onclick=async()=>{let sched=DB.get('schedule',{cursor:0,reschedules:[]});const cycle=['Pull A','Legs + Abs','Rest / Steps','Push A','Shoulders + Arms','Pull B + Upper Chest','Rest'];let skipped=cycle[sched.cursor]||'Session';sched.reschedules=sched.reschedules||[];sched.reschedules.push({sessionIndex:sched.cursor,session:skipped,action:'Skipped — moved on',date:new Date().toISOString()});sched.cursor=Math.min(sched.cursor+1,cycle.length-1);DB.set('schedule',sched);try{await BBDB.saveScheduleState(sched)}catch(e){}modal.classList.add('hidden');await renderCycle()};
let chooseSession=document.getElementById('chooseSession');if(chooseSession)chooseSession.onclick=()=>{modal.classList.add('hidden');document.getElementById('week')?.scrollIntoView({behavior:'smooth'});document.getElementById('cycleDetail').innerHTML='<p class="smallnote">Tap any session below, then choose <b>Train this session today</b>. Your normal sequence is preserved.</p>'};

let hist=document.getElementById('history');
if(hist){
  let h=DB.get('history',[]);
  hist.innerHTML=h.length?h.map((x,idx)=>{
    let lines=(x.exercises||[]).map(e=>{
      let sets=(e.sets||[]).filter(s=>s.completed).map(s=>`${s.kg||'?'} kg × ${s.reps||'?'} @ ${s.rir||'?'} RIR`).join(' · ');
      return sets?`<div><b>${e.performed||e.name}</b>: ${sets}</div>`:'';
    }).join('');
    return `<div class='historySession'><b>${x.name}</b><button class='editdate' data-editdate='${idx}'>Edit date</button><p class='muted'>${new Date(x.date).toLocaleString()} · ${x.completedSets||0} working sets</p><div class='historySets'>${lines||'Session saved without detailed set data.'}</div></div>`
  }).join(''):'<p class="muted">No completed sessions stored on this device yet.</p>';
  document.querySelectorAll('[data-editdate]').forEach(btn=>btn.onclick=()=>{
    let i=+btn.dataset.editdate, arr=DB.get('history',[]);
    let current=new Date(arr[i].date); let value=prompt('Workout date (YYYY-MM-DD)',current.toISOString().slice(0,10));
    if(value && /^\d{4}-\d{2}-\d{2}$/.test(value)){arr[i].date=value+'T12:00:00';DB.set('history',arr);location.reload()}
  });
}

function reminderSummary(){
 const box=document.getElementById('nextCheckin');if(!box)return;
 const defs=[{id:'macros',name:'Daily macros',priority:'Required',frequency:'daily',day:null,time:'20:30',enabled:true},{id:'weighin',name:'Friday weigh-in',priority:'Required',frequency:'weekly',day:5,time:'08:00',enabled:true},{id:'progress',name:'Waist + progress photos',priority:'Recommended',frequency:'fortnightly',day:5,time:'08:00',enabled:true},{id:'measurements',name:'Full measurements',priority:'Recommended',frequency:'monthly',day:5,time:'08:00',enabled:true},{id:'inbody',name:'InBody',priority:'Optional',frequency:'monthly',day:5,time:'08:00',enabled:true}];
 let rs=DB.get('reminders',null);if(!rs){rs=defs;DB.set('reminders',rs)}let h=DB.get('checkinHistory',[]);
 const last=id=>h.filter(x=>x.id===id).sort((a,b)=>new Date(b.date)-new Date(a.date))[0]?.date;
 const due=r=>{let n=new Date(),l=last(r.id),d=l?new Date(l):null,x;if(r.frequency==='daily'){x=new Date(n);let [a,b]=r.time.split(':');x.setHours(+a,+b,0,0);if(d&&d>=x)x.setDate(x.getDate()+1);return x}if(r.frequency==='weekly'||r.frequency==='fortnightly'){if(d){x=new Date(d);x.setDate(x.getDate()+(r.frequency==='weekly'?7:14))}else{x=new Date(n);x.setDate(x.getDate()+((+r.day-x.getDay()+7)%7))}let [a,b]=r.time.split(':');x.setHours(+a,+b,0,0);return x}x=d?new Date(d):new Date(n);if(d)x.setMonth(x.getMonth()+1);else{x.setDate(1);if(x<n)x.setMonth(x.getMonth()+1)}let [a,b]=r.time.split(':');x.setHours(+a,+b,0,0);return x};
 let active=rs.filter(r=>r.enabled).map(r=>({...r,due:due(r)})).sort((a,b)=>a.due-b.due),over=active.filter(r=>r.due<=new Date()),n=over[0]||active[0];if(!n){box.innerHTML='<p class="muted">No reminders enabled.</p>';return}box.innerHTML='<div class="dashcheck '+(over.length?'overdue':'')+'"><div><span class="priority '+n.priority.toLowerCase()+'">'+n.priority+'</span><b>'+(over.length?over.length+' overdue':n.name)+'</b><small>'+(over.length?n.name:'Due '+n.due.toLocaleString('en-GB'))+'</small></div><a href="reminders.html">'+(over.length?'REVIEW':'OPEN')+' →</a></div>';
}
reminderSummary();

(async()=>{const box=document.getElementById('coachTodayText');if(!box)return;try{const r=await BBDB.latestCoachReview();box.innerHTML=r?'<p>'+String(r.summary).replace(/</g,'&lt;')+'</p><p><b>Next:</b> '+String(r.decision||'No change').replace(/</g,'&lt;')+'</p>':'<p class="muted">Complete a workout or body check-in to generate your first automatic coaching review.</p>'}catch(e){box.innerHTML='<p class="muted">Coach review unavailable.</p>'}})();
const macroBtn=document.getElementById('macroCheckinBtn'),macroForm=document.getElementById('macroForm'),saveMacros=document.getElementById('saveMacrosBtn');
if(macroBtn)macroBtn.onclick=async()=>{macroForm.classList.toggle('hidden');try{const last=await BBDB.latestMacroCheckin();const d=last?.extracted_data||{};if(d.calories!=null)document.getElementById('macroCalories').value=d.calories;if(d.protein_g!=null)document.getElementById('macroProtein').value=d.protein_g;if(d.carbs_g!=null)document.getElementById('macroCarbs').value=d.carbs_g;if(d.fat_g!=null)document.getElementById('macroFat').value=d.fat_g}catch(e){}};
if(saveMacros)saveMacros.onclick=async()=>{const msg=document.getElementById('macroMsg'),p={calories:document.getElementById('macroCalories').value,protein_g:document.getElementById('macroProtein').value,carbs_g:document.getElementById('macroCarbs').value,fat_g:document.getElementById('macroFat').value};if(Object.values(p).some(v=>v==='')){msg.textContent='Enter calories, protein, carbs and fat.';return}saveMacros.disabled=true;saveMacros.textContent='Saving…';try{const saved=await BBDB.saveMacroCheckin(p);saveMacros.textContent='Coach reviewing…';const review=await BBDB.coachReview('nutrition',{date:new Date().toISOString(),...p},saved.id);msg.innerHTML='Saved ✓<br><b>Coach:</b> '+String(review.summary).replace(/</g,'&lt;')+'<br><b>Next:</b> '+String(review.decision||'No change').replace(/</g,'&lt;');saveMacros.textContent='Saved & reviewed ✓';setTimeout(()=>{saveMacros.disabled=false;saveMacros.textContent='Save & Review'},1500)}catch(e){msg.textContent='Not saved: '+e.message;saveMacros.disabled=false;saveMacros.textContent='Save & Review'}};

(async()=>{const body=document.getElementById('blockStageBody'),badge=document.getElementById('blockStageBadge');if(!body)return;try{const b=await BBDB.activeBlock();if(!b?.start_date){body.innerHTML='<p class="muted">No dated training block assigned.</p>';return}const start=new Date(b.start_date+'T00:00:00Z'),now=new Date(),day=Math.max(0,Math.floor((Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())-start.getTime())/86400000)),duration=Number(b.duration_weeks||12),week=Math.min(duration,Math.floor(day/7)+1),recovery=(b.recovery_weeks||[6,12]).map(Number),isRecovery=recovery.includes(week),phase=isRecovery?'RECOVERY WEEK':(week<recovery[0]?'BUILD 1':'BUILD 2'),nextRecovery=recovery.find(x=>x>week),pct=Math.min(100,Math.round((week/duration)*100));badge.textContent=phase;body.innerHTML='<h3 style="font-size:1.55rem;margin:.3rem 0">Week '+week+' of '+duration+'</h3><div style="height:8px;background:var(--soft);border-radius:9px;overflow:hidden;margin:10px 0 12px"><div style="height:100%;width:'+pct+'%;background:var(--accent)"></div></div><p class="muted">'+(isRecovery?'Reduce training stress. Light resistance, mobility, easy cardio/steps or complete rest. No progression targets this week.':(nextRecovery?(nextRecovery-week)+' week'+(nextRecovery-week===1?'':'s')+' until Recovery Week. Continue normal progressive training.':'Final build phase.'))+'</p>'}catch(e){body.innerHTML='<p class="muted">Block stage unavailable.</p>'}})();
