const DEFAULT_REMINDERS=[
{id:'macros',name:'Daily macros',detail:'Submit daily calories and macros',priority:'Required',frequency:'daily',day:null,time:'20:30',enabled:true},
{id:'weighin',name:'Friday weigh-in',detail:'Morning bodyweight',priority:'Required',frequency:'weekly',day:5,time:'06:00',enabled:true},
{id:'progress',name:'Waist + progress photos',detail:'Waist measurement and progress photos',priority:'Recommended',frequency:'fortnightly',day:5,time:'06:00',enabled:true},
{id:'measurements',name:'Full measurements',detail:'Waist · chest · arms · thighs · calves',priority:'Recommended',frequency:'monthly',day:5,time:'06:00',enabled:true},
{id:'inbody',name:'InBody',detail:'Upload latest InBody result',priority:'Optional',frequency:'monthly',day:5,time:'07:00',enabled:true}
];
function getReminders(){let x=DB.get('reminders',null);if(!x){x=DEFAULT_REMINDERS;DB.set('reminders',x)}return x}
function history(){return DB.get('checkinHistory',[])}
function lastDone(id){return history().filter(x=>x.id===id).sort((a,b)=>new Date(b.date)-new Date(a.date))[0]?.date||null}
function dueDate(r){let now=new Date(),last=lastDone(r.id),d=last?new Date(last):null;if(r.frequency==='daily'){let x=new Date(now);let [h,m]=r.time.split(':');x.setHours(+h,+m,0,0);if(d&&d>=x)x.setDate(x.getDate()+1);return x}if(r.frequency==='weekly'||r.frequency==='fortnightly'){let gap=r.frequency==='weekly'?7:14;if(d){let x=new Date(d);x.setDate(x.getDate()+gap);let [h,m]=r.time.split(':');x.setHours(+h,+m,0,0);return x}let x=new Date(now),add=(+r.day-x.getDay()+7)%7;x.setDate(x.getDate()+add);let [h,m]=r.time.split(':');x.setHours(+h,+m,0,0);return x}if(r.frequency==='monthly'){let x=d?new Date(d):new Date(now);if(d)x.setMonth(x.getMonth()+1);else{x.setDate(1);if(x<now)x.setMonth(x.getMonth()+1)}let [h,m]=r.time.split(':');x.setHours(+h,+m,0,0);return x}}
function status(r){if(!r.enabled)return'off';let due=dueDate(r),now=new Date();return due<=now?'overdue':'upcoming'}
function fmt(d){return new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)}
function render(){let rs=getReminders(),box=document.getElementById('reminderList');box.innerHTML=rs.map(r=>{let s=status(r),due=r.enabled?fmt(dueDate(r)):'Off';return '<div class="reminderrow '+s+'" data-edit="'+r.id+'"><div class="remindermain"><div><span class="priority '+r.priority.toLowerCase()+'">'+r.priority+'</span><b>'+r.name+'</b><small>'+r.detail+'</small></div><div class="reminderright"><strong>'+(s==='overdue'?'OVERDUE':due)+'</strong><small>'+r.frequency+(r.frequency!=='daily'?' · '+['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][r.day]:'')+' · '+r.time+'</small></div></div><div class="reminderactions"><button data-done="'+r.id+'" class="primary">Mark complete</button><button data-edit="'+r.id+'">Edit</button></div></div>'}).join('');let h=history();document.getElementById('historyCount').textContent=h.length+' submissions';document.getElementById('checkinHistory').innerHTML=h.length?h.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,40).map(x=>'<div class="checkinhistory"><b>'+x.name+'</b><span>'+new Date(x.date).toLocaleString('en-GB')+'</span></div>').join(''):'<p class="muted">No check-ins completed yet.</p>';bind()}
function bind(){document.querySelectorAll('[data-done]').forEach(b=>b.onclick=e=>{e.stopPropagation();let r=getReminders().find(x=>x.id===b.dataset.done),h=history();h.unshift({id:r.id,name:r.name,date:new Date().toISOString()});DB.set('checkinHistory',h);render()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{if(e.target.dataset.done)return;openEdit(b.dataset.edit)})}
let editing=null;function openEdit(id){editing=id;let r=getReminders().find(x=>x.id===id);document.getElementById('modalTitle').textContent=r.name;editPriority.value=r.priority;editFrequency.value=r.frequency;editDay.value=r.day??5;editTime.value=r.time;editEnabled.checked=r.enabled;reminderModal.classList.remove('hidden')}saveReminder.onclick=()=>{let rs=getReminders(),r=rs.find(x=>x.id===editing);r.priority=editPriority.value;r.frequency=editFrequency.value;r.day=+editDay.value;r.time=editTime.value;r.enabled=editEnabled.checked;DB.set('reminders',rs);reminderModal.classList.add('hidden');render()};cancelReminder.onclick=()=>reminderModal.classList.add('hidden');
const ns=document.getElementById('notifyState'),nb=document.getElementById('notifyBtn');function notifyState(){if(!('Notification'in window)){ns.textContent='Not supported';nb.disabled=true;return}ns.textContent=Notification.permission==='granted'?'Enabled':Notification.permission==='denied'?'Blocked':'Off';nb.textContent=Notification.permission==='granted'?'Notifications enabled':'Enable notifications'}nb.onclick=async()=>{if(!('Notification'in window))return;await Notification.requestPermission();notifyState();if(Notification.permission==='granted')new Notification('Check-in reminders enabled',{body:'The app will alert you to due coaching data when active.'})};notifyState();render();